
exports.up = function(knex) {
    return knex.schema.createTable("cdc", table => {
        table.increments("id").primary();
        table.date("date").notNullable();
        table
        .integer("state_id")
        .unsigned()
        .notNullable()
        .references("id")
        .inTable("states")
        .onUpdate("CASCADE")
        .onDelete("CASCADE");
        table.string("name").notNullable();
        table.bigInteger("Total_Doses_Delivered");
        table.bigInteger("Doses_Delivered_per_100K");
        table.bigInteger("18+_Doses_Delivered_per_100K")
        table.bigInteger("Total_Doses_Administered");
        table.bigInteger("Doses_Administered_per_100k");
        table.bigInteger("18+_Doses_Administered");
        table.bigInteger("18+_Doses_Administered_per_100K");
        table.bigInteger("People_with_at_least_One_Dose");
        table.decimal("Percent_of_Total_Pop_with_at_least_One_Dose");
        table.bigInteger("People_18+_with_at_least_One_Dose");
        table.decimal("Percent_of_18+_Pop_with_at_least_One_Dose");
        table.bigInteger("People_Fully_Vaccinated");
        table.bigInteger("Percent_of_Total_Pop_Fully_Vaccinated");
        table.bigInteger("People_18+_Fully_Vaccinated");
        table.decimal("Percent_of_18+_Pop_Fully_Vaccinated");
        table.bigInteger("Total_Number_of_Pfizer_doses_delivered");
        table.bigInteger("Total_Number_of_Moderna_doses_delivered");
        table.bigInteger("Total_Number_of_Janssen_doses_delivered");
        table.bigInteger("Total_Number_of_doses_from_unknown_manufacturer_delivered");
        table.bigInteger("Total_Number_of_Janssen_doses_administered");
        table.bigInteger("Total_Number_of_Moderna_doses_administered");
        table.bigInteger("Total_Number_of_Pfizer_doses_adminstered");
        table.bigInteger("Total_Number_of_doses_from_unknown_manufacturer_administered");
        table.bigInteger("People_Fully_Vaccinated_Moderna_Resident");
        table.bigInteger("People_Fully_Vaccinated_Pfizer_Resident");
        table.bigInteger("People_Fully_Vaccinated_Janssen_Resident");
        table.bigInteger("People_Fully_Vaccinated_Unknown_2-dose_manufacturer_Resident");
        table.bigInteger("People_18+_Fully_Vaccinated_Moderna_Resident");
        table.bigInteger("People_18+_Fully_Vaccinated_Pfizer_Resident");
        table.bigInteger("People_18+_Fully_Vaccinated_Janssen_Resident");
        table.bigInteger("People_18+_Fully_Vaccinated_Unknown_2-dose_manufacturer_Resident");
        table.bigInteger("People_with_2_Doses");
        table.decimal("Percent_of_Total_Pop_with_1+_Doses");
        table.bigInteger("People_18+_with_1+_Doses");
        table.bigInteger("Percent_of_18+_Pop_with_1+_Doses");
        table.decimal("Percent_of_Total_Pop_with_2_Doses");
        table.bigInteger("People_18+_with_2_Doses");
        table.bigInteger("Percent_of_18+_Pop_with_2_Doses");
        table.bigInteger("People_with_1+_Doses");
        table.bigInteger("People_65+_with_at_least_One_Dose");
        table.decimal("Percent_of_65+_Pop_with_at_least_One_Dose");
        table.bigInteger("People_65+_Fully_Vaccinated");
        table.bigInteger("Percent_of_65+_Pop_Fully_Vaccinated");
        table.bigInteger("People_65+_Fully_Vaccinated_Moderna_Resident");
        table.bigInteger("People_65+_Fully_Vaccinated_Pfizer_Resident");
        table.bigInteger("People_65+_Fully_Vaccinated_Janssen_Resident");
        table.bigInteger("People_65+_Fully_Vaccinated_Unknown_2-dose_Manuf_Resident");
        table.bigInteger("65+_Doses_Administered");
        table.bigInteger("Doses_Administered_per_100k_of_65+_pop");
        table.bigInteger("Doses_Delivered_per_100k_of_65+_pop");
    })
  };
  
  exports.down = function(knex) {
    return knex.schema.dropTable("cdc")
  };
